### ISSUE TITLE
Errors running hpcdiag on NDv4(40GB A100)

### ISSUE THREAD

**Issue by garvct** [Azure/azhpc-diagnostics#62] opened 2021-11-04 00:32 UTC
sudo ${HPCDIAG_EXE_DIR}/gather_azhpc_vm_diagnostics.sh -d . --gpu-level=3 --mem-level=1

etc
Running Nvidia GPU Diagnostics
        Querying Nvidia GPU Info, writing to {output}/Nvidia/nvidia-smi-q.out
        Running plain nvidia-smi, writing to {output}/Nvidia/nvidia-smi.out
        Dumping Nvidia GPU internal state to {output}/Nvidia/nvidia-debugdump.zip
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
ERROR: GetCaptureBufferSize failed, Unknown Error, bufSize: 0x0
ERROR: internal_getDumpBuffer failed, return code: 0x3e7
ERROR: internal_dumpGpuComponent() failed, return code: 0x3e7
        Temporarily starting nv-hostengine

etc

Checking for common issues
        Checking for GPUs with corrupted infoROM
        Checking for GPUs with row remapping failures
        Checking for GPUs that don't appear in nvidia-smi
        Checking PCIe speed training for GPUs
        Could not find pkey 0 for device mlx5_ib0
        Could not find pkey 1 for device mlx5_ib0
        Could not find pkey 0 for device mlx5_ib1
        Could not find pkey 1 for device mlx5_ib1
        Could not find pkey 0 for device mlx5_ib2
        Could not find pkey 1 for device mlx5_ib2
        Could not find pkey 0 for device mlx5_ib3
        Could not find pkey 1 for device mlx5_ib3
        Could not find pkey 0 for device mlx5_ib4
        Could not find pkey 1 for device mlx5_ib4
        Could not find pkey 0 for device mlx5_ib5
        Could not find pkey 1 for device mlx5_ib5
        Could not find pkey 0 for device mlx5_ib6
        Could not find pkey 1 for device mlx5_ib6
        Could not find pkey 0 for device mlx5_ib7
        Could not find pkey 1 for device mlx5_ib7

Are these errors normal on NDv4? 
I ran on multiple NDv4 VM's and got the same errors above.

**Comment by tlcyr4** [comment] 2021-11-04 23:32
For the Nvidia errors, those have been showing up. I'll note that those are not errors generated by HPCDiag; they are from nvidia-debugdump, and as it is written now, HPCDiag will show you those errors while it's running. They are also stored in the output tarball. In my view, unless there's a different way that we should be running Nvidia's tool, these are legitimate error messages that should be shown to the user since a vendor tool is generating them. So it's at most a UI consideration for HPCDiag, since it looks scary and there aren't any well-defined actions in response to those messages.

For the pkey messages, that is actually a bug that I now need to fix in HPCDiag. I was able to reproduce it by running with the `-d .` option you used.

You can see the problem more clearly in hpcdiag.err (part of the overall tool output):
```
+ find /sys/class/infiniband/mlx5_ib0/ -path '*pkeys/*' -execdir cp '{}' ./fdaac470-7daa-449d-9c3d-73abb26ebfba.2021-11-04.UTC22.59.14/Infiniband/mlx5_ib0/pkeys ';'
cp: cannot create regular file './fdaac470-7daa-449d-9c3d-73abb26ebfba.2021-11-04.UTC22.59.14/Infiniband/mlx5_ib0/pkeys': No such file or directory
cp: cannot create regular file './fdaac470-7daa-449d-9c3d-73abb26ebfba.2021-11-04.UTC22.59.14/Infiniband/mlx5_ib0/pkeys': No such file or directory
cp: cannot create regular file './fdaac470-7daa-449d-9c3d-73abb26ebfba.2021-11-04.UTC22.59.14/Infiniband/mlx5_ib0/pkeys': No such file or directory
```
When compared to what happens if I don't use `-d .`:
```
+ find /sys/class/infiniband/mlx5_ib0/ -path '*pkeys/*' -execdir cp '{}' /home/tigarcyr/fdaac470-7daa-449d-9c3d-73abb26ebfba.2021-11-04.UTC22.52.09/Infiniband/mlx5_ib0/pkeys ';'
```
it seems that resolving `.` to a real path before passing to the `find` command makes the difference. I verified that with a manual test. I guess that, inside the subprocess that `find` creates, `.` does not get resolved to anything, and filepaths with symbols like it in them will cause failures.

I'm not even sure if that's the intended behavior for `find`, but I will be fixing this by resolving the path before passing it in to `find`.

So thank you for bringing this up. I'm starting work on the fix, and, in the meantime, my recommendation for mitigating the issue is to avoid using the `-d` option with any paths that use globbing or special characters.

**Comment by tlcyr4** [comment] 2021-11-04 23:51
@garvct Hotfix for this is on the main branch now. Leaving the Issue open while I write unit tests to keep the bug from coming back.

**Closed** 2021-11-05 19:09 UTC
Labels: bug
